### PR TITLE
Make releasable version of notebooks

### PR DESCRIPTION
**Pull request by KedoKudo**
Main changes in this PR

* Simply the top-level folder structure
  * Reduce the number of file visible at the root level
  * Change the name of the installation script to reflect its functionality 
  * Remove outdated files
* Add support for Docker
  * Image is built and published on Dockerhub
* Update instructions in `Readme.md`

### CODE REVIEW

**Comment by KedoKudo** [comment]
@JeanBilheux 
Additional instructions on how to use the docker env are added as discussed.  Please let me know if there is anything else need to be updated.

**Comment by JeanBilheux** [comment]
I think we should remove the instructions regarding docker in the README to avoid the confusion with the users as this is not working right now. 
Instead of ```git clone ...```, can we clone a specific tag instead, stable release version?

**Comment by JeanBilheux** [comment]
Thanks @KedoKudo. I'm trying to minimize the number of commands the user will have to type and things they will need to adapt as some of our users are really allergic to any command line input 👍

**Comment by KedoKudo** [comment]
@JeanBilheux Could you take another look at the updated version of instructions, in case there is anything I missed?

**Comment by JeanBilheux** [comment]
I like it. We may need to point to a branch/tag that has a better name than the one I picked "make_releasable...etc" but that will be easy to change.

**Pull request merged**
